"""
app/schemas/report_schemas.py

Request and response schemas for clinical outputs and compliance.

Covers:
- MedicalReport     (AI-assisted report lifecycle)
- MedicalImage      (uploaded images + AI analysis)
- LabReport         (uploaded lab documents + AI interpretation)
- AuditLog          (compliance trail — read-only from API perspective)

AI field design
---------------
ai_medications and ai_recommendations are JSONB in the database. The API
exposes them through typed Pydantic models (AIm edication, list[str]) so
the contract is explicit and clients don't have to parse raw JSON.

On the way IN (voice transcription, approval) the service layer populates
these from the AI module output. On the way OUT (responses) they are
serialized as structured objects.

Nesting strategy
----------------
MedicalReportResponse embeds VisitSummary (id + status + start_time).
It does NOT re-embed MedicalImage or LabReport lists — those live on the
visit and are fetched via their own endpoints to keep payloads lean.

AuditLog is read-only — no Create/Update schemas exist.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.core.constants import AuditAction, ImageType, ReportStatus
from app.schemas.clinic_schemas import VisitSummary
from app.schemas.user_schemas import DoctorSummary


# ===========================================================================
# AI structured output sub-models
# ===========================================================================

class AIMedication(BaseModel):
    """
    A single medication entry as generated by the medical NLP module.
    Stored as one element inside the ai_medications JSONB array.
    """

    model_config = ConfigDict(from_attributes=True)

    name:      str = Field(description="Drug name (generic or brand).")
    dose:      str | None = Field(default=None, description="e.g. '500mg', '10ml'.")
    frequency: str | None = Field(default=None, description="e.g. 'twice daily', 'every 8 hours'.")
    duration:  str | None = Field(default=None, description="e.g. '7 days', '2 weeks'.")
    route:     str | None = Field(default=None, description="e.g. 'oral', 'topical', 'IV'.")
    notes:     str | None = Field(default=None, description="Special instructions.")


class AIReportDraft(BaseModel):
    """
    Structured AI output returned after voice transcription processing.
    Presented to the doctor for review before report approval.

    This schema is returned by the AI processing endpoint but is NOT
    stored directly — its fields map to MedicalReport columns.
    """

    model_config = ConfigDict(from_attributes=True)

    transcription:    str = Field(description="Verbatim speech-to-text output.")
    ai_diagnosis:     str | None = Field(
        default=None,
        description="SOAP-formatted diagnostic summary generated by medical NLP.",
    )
    ai_medications:     list[AIMedication] = Field(
        default_factory=list,
        description="Suggested medication list with structured dose/frequency.",
    )
    ai_recommendations: list[str] = Field(
        default_factory=list,
        description="Free-text lifestyle and follow-up recommendations.",
    )
    ai_follow_up: str | None = Field(
        default=None,
        description="Suggested follow-up interval e.g. 'Return in 2 weeks if symptoms persist'.",
    )


# ===========================================================================
# MEDICAL REPORT
# ===========================================================================

class MedicalReportCreate(BaseModel):
    """
    Payload for POST /visits/{visit_id}/report  (doctor only).

    Used when a report is created without voice — the doctor types findings
    directly. For voice-driven reports the service layer creates the report
    automatically after transcription.

    All AI fields are optional here because the service may populate them
    from AI output rather than from this payload.
    """

    model_config = ConfigDict(from_attributes=True)

    doctor_voice_transcription: str | None = Field(
        default=None,
        description="Raw transcription text if already obtained from speech-to-text.",
    )
    ai_diagnosis:               str | None = None
    ai_medications:             list[AIMedication] | None = None
    ai_recommendations:         list[str] | None = None
    ai_follow_up:               str | None = Field(default=None, max_length=500)
    doctor_notes:               str | None = Field(
        default=None,
        description="Doctor's manual additions or corrections to AI-generated content.",
    )


class MedicalReportUpdate(BaseModel):
    """
    Payload for PATCH /reports/{id}  (doctor only).

    Used by the doctor to edit the AI draft before approval.
    All fields optional — partial updates supported.
    """

    model_config = ConfigDict(from_attributes=True)

    doctor_voice_transcription: str | None = None
    ai_diagnosis:               str | None = None
    ai_medications:             list[AIMedication] | None = None
    ai_recommendations:         list[str] | None = None
    ai_follow_up:               str | None = Field(default=None, max_length=500)
    doctor_notes:               str | None = None


class MedicalReportStatusUpdate(BaseModel):
    """
    Dedicated payload for PATCH /reports/{id}/status  (doctor only).
    Separates lifecycle transitions (draft → approved → finalized)
    from field edits. The service layer validates allowed transitions.
    """

    model_config = ConfigDict(from_attributes=True)

    status: ReportStatus = Field(
        description=(
            "Target lifecycle status. "
            "Valid transitions: draft→reviewed, reviewed→approved, approved→finalized."
        ),
    )


class MedicalReportResponse(BaseModel):
    """
    Full medical report as returned to clients.

    ai_medications is exposed as a structured list of AIMedication objects
    rather than raw JSON, giving clients a typed contract.
    ai_recommendations is a list of plain strings.

    Embeds:
    - visit: VisitSummary (id, appointment_id, status, start_time)
    - doctor: DoctorSummary (id, name, specialization)
    """

    model_config = ConfigDict(from_attributes=True)

    id:       int
    visit_id: int
    doctor_id: int
    status:   ReportStatus

    doctor_voice_transcription: str | None
    ai_diagnosis:               str | None
    ai_medications:             list[AIMedication] | None
    ai_recommendations:         list[str] | None
    ai_follow_up:               str | None
    doctor_notes:               str | None

    # Shallow embeds
    visit:  VisitSummary
    doctor: DoctorSummary

    # Timestamps included on reports — clinicians need to know when generated
    created_at: datetime
    updated_at: datetime


class MedicalReportSummary(BaseModel):
    """
    Compact report for listing endpoints (e.g. GET /visits/{id}/history).
    """

    model_config = ConfigDict(from_attributes=True)

    id:         int
    visit_id:   int
    doctor_id:  int
    status:     ReportStatus
    created_at: datetime


# ===========================================================================
# MEDICAL IMAGE
# ===========================================================================

class MedicalImageCreate(BaseModel):
    """
    Payload for POST /visits/{visit_id}/images  (doctor or assistant).

    image_url is set by the service layer after the file is saved to storage.
    Clients send the binary file via multipart/form-data — this schema
    carries the metadata that accompanies the upload.
    """

    model_config = ConfigDict(from_attributes=True)

    image_type: ImageType = Field(
        description="Modality of the image. Drives AI analysis pipeline selection.",
    )
    doctor_notes: str | None = Field(
        default=None,
        description="Initial clinical notes on this image. Can be updated later.",
    )


class MedicalImageUpdate(BaseModel):
    """
    Payload for PATCH /images/{id}  (doctor only).
    Used to update the doctor's notes after AI analysis is complete.
    image_url and image_type are immutable once set.
    """

    model_config = ConfigDict(from_attributes=True)

    doctor_notes: str | None = None


class MedicalImageResponse(BaseModel):
    """
    Full medical image record including AI diagnosis and doctor notes.
    image_url is the resolved download path.
    """

    model_config = ConfigDict(from_attributes=True)

    id:           int
    visit_id:     int
    image_url:    str
    image_type:   ImageType
    ai_diagnosis: str | None
    doctor_notes: str | None
    created_at:   datetime


# ===========================================================================
# LAB REPORT
# ===========================================================================

class LabReportCreate(BaseModel):
    """
    Payload for POST /visits/{visit_id}/lab-reports  (doctor or assistant).

    report_url is set by the service layer after file storage.
    Clients send the binary PDF/image via multipart/form-data.
    This schema carries metadata only.
    """

    model_config = ConfigDict(from_attributes=True)

    # No required fields beyond the file itself (handled by multipart).
    # Metadata fields are all optional at upload time.
    pass


class LabReportUpdate(BaseModel):
    """
    Payload for PATCH /lab-reports/{id}  (doctor only).
    Allows the doctor to add notes after AI interpretation is complete.
    """

    model_config = ConfigDict(from_attributes=True)

    # Currently only the AI summary is updatable post-upload.
    # Extend this schema if doctor annotation fields are added to the model.
    ai_interpreted_summary: str | None = Field(
        default=None,
        description="Override or supplement the AI-generated interpretation.",
    )


class LabReportResponse(BaseModel):
    """
    Full lab report record including AI interpretation and original extracted text.
    report_url is the resolved download path.
    """

    model_config = ConfigDict(from_attributes=True)

    id:                     int
    visit_id:               int
    report_url:             str
    ai_interpreted_summary: str | None
    original_text:          str | None
    created_at:             datetime


# ===========================================================================
# AUDIT LOG  (read-only — no Create or Update schemas)
# ===========================================================================

class AuditLogResponse(BaseModel):
    """
    A single audit trail entry as returned by GET /admin/audit-logs.

    The `details` field contains a JSON-serialised snapshot of what changed.
    It is returned as a plain string here (not parsed) so that the schema
    remains stable regardless of evolving audit payload structures.
    Clients that need to introspect audit detail can JSON-parse the string.
    """

    model_config = ConfigDict(from_attributes=True)

    id:          int
    user_id:     int | None = Field(
        description="PK of the user who performed the action. Null for system events.",
    )
    action:      AuditAction
    entity_type: str | None = Field(
        description="The type of record affected (e.g. 'patient', 'appointment').",
    )
    entity_id:   int | None = Field(
        description="PK of the affected record.",
    )
    details:     str | None = Field(
        description="JSON-serialised change snapshot. Parse client-side if needed.",
    )
    ip_address:  str | None
    created_at:  datetime


class AuditLogFilter(BaseModel):
    """
    Query parameters for GET /admin/audit-logs.
    All filters are optional and combinable.
    """

    model_config = ConfigDict(from_attributes=True)

    user_id:     int | None = Field(default=None, description="Filter by acting user.")
    action:      AuditAction | None = Field(default=None, description="Filter by action type.")
    entity_type: str | None = Field(default=None, description="Filter by affected entity type.")
    entity_id:   int | None = Field(default=None, description="Filter by affected entity PK.")
    date_from:   datetime | None = Field(default=None, description="Earliest created_at (inclusive).")
    date_to:     datetime | None = Field(default=None, description="Latest created_at (inclusive).")