"""initial

Revision ID: 5398b4cd41a3
Revises: 
Create Date: 2026-02-11 10:31:07.407755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5398b4cd41a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('CHRONIC', 'ALLERGY', name='condition_category'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_medical_conditions_name')
    )
    op.create_index('ix_medical_conditions_category', 'medical_conditions', ['category'], unique=False)
    op.create_index('ix_medical_conditions_name', 'medical_conditions', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id', name='uq_patients_national_id')
    )
    op.create_index('ix_patients_last_name', 'patients', ['last_name'], unique=False)
    op.create_index('ix_patients_national_id', 'patients', ['national_id'], unique=False)
    op.create_index('ix_patients_phone', 'patients', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Login identifier — must be globally unique across all roles.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment="bcrypt hash of the user's password. Never store plaintext."),
    sa.Column('role', sa.Enum('DOCTOR', 'ASSISTANT', 'ADMIN', name='user_role'), nullable=False, comment="Determines which profile table this user's details live in."),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Soft-deletion flag. Deactivated users cannot log in.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_admins_user_id')
    )
    op.create_index('ix_admins_user_id', 'admins', ['user_id'], unique=False)
    op.create_table('assistants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('clinic_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_assistants_user_id')
    )
    op.create_index('ix_assistants_clinic_name', 'assistants', ['clinic_name'], unique=False)
    op.create_index('ix_assistants_user_id', 'assistants', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='FK to users. CASCADE ensures profile is removed with the account.'),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('clinic_name', sa.String(length=200), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number', name='uq_doctors_license_number'),
    sa.UniqueConstraint('user_id', name='uq_doctors_user_id')
    )
    op.create_index('ix_doctors_clinic_name', 'doctors', ['clinic_name'], unique=False)
    op.create_index('ix_doctors_specialization', 'doctors', ['specialization'], unique=False)
    op.create_index('ix_doctors_user_id', 'doctors', ['user_id'], unique=False)
    op.create_table('patient_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('diagnosed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['medical_conditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'condition_id', name='uq_patient_conditions_patient_condition')
    )
    op.create_index('ix_patient_conditions_condition_id', 'patient_conditions', ['condition_id'], unique=False)
    op.create_index('ix_patient_conditions_patient_id', 'patient_conditions', ['patient_id'], unique=False)
    op.create_table('appointment_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('default_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_types_doctor_id', 'appointment_types', ['doctor_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_type_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointment_status'), server_default=sa.text("'SCHEDULED'"), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_appointment_type_id', 'appointments', ['appointment_type_id'], unique=False)
    op.create_index('ix_appointments_doctor_id', 'appointments', ['doctor_id'], unique=False)
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_start_time', 'appointments', ['start_time'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('blood_pressure', sa.String(length=20), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='visit_status'), server_default=sa.text("'IN_PROGRESS'"), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', name='uq_visits_appointment_id')
    )
    op.create_index('ix_visits_appointment_id', 'visits', ['appointment_id'], unique=False)
    op.create_index('ix_visits_start_time', 'visits', ['start_time'], unique=False)
    op.create_index('ix_visits_status', 'visits', ['status'], unique=False)
    op.create_table('lab_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('report_url', sa.String(length=500), nullable=False),
    sa.Column('ai_interpreted_summary', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_reports_visit_id', 'lab_reports', ['visit_id'], unique=False)
    op.create_table('medical_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.Enum('XRAY', 'SKIN', name='image_type'), nullable=False),
    sa.Column('ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_images_image_type', 'medical_images', ['image_type'], unique=False)
    op.create_index('ix_medical_images_visit_id', 'medical_images', ['visit_id'], unique=False)
    op.create_table('medical_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_voice_transcription', sa.Text(), nullable=True),
    sa.Column('ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('ai_medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_follow_up', sa.String(length=500), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='report_status'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', name='uq_medical_reports_visit_id')
    )
    op.create_index('ix_medical_reports_created_at', 'medical_reports', ['created_at'], unique=False)
    op.create_index('ix_medical_reports_doctor_id', 'medical_reports', ['doctor_id'], unique=False)
    op.create_index('ix_medical_reports_status', 'medical_reports', ['status'], unique=False)
    op.create_index('ix_medical_reports_visit_id', 'medical_reports', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medical_reports_visit_id', table_name='medical_reports')
    op.drop_index('ix_medical_reports_status', table_name='medical_reports')
    op.drop_index('ix_medical_reports_doctor_id', table_name='medical_reports')
    op.drop_index('ix_medical_reports_created_at', table_name='medical_reports')
    op.drop_table('medical_reports')
    op.drop_index('ix_medical_images_visit_id', table_name='medical_images')
    op.drop_index('ix_medical_images_image_type', table_name='medical_images')
    op.drop_table('medical_images')
    op.drop_index('ix_lab_reports_visit_id', table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index('ix_visits_status', table_name='visits')
    op.drop_index('ix_visits_start_time', table_name='visits')
    op.drop_index('ix_visits_appointment_id', table_name='visits')
    op.drop_table('visits')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_start_time', table_name='appointments')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_index('ix_appointments_doctor_id', table_name='appointments')
    op.drop_index('ix_appointments_appointment_type_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_appointment_types_doctor_id', table_name='appointment_types')
    op.drop_table('appointment_types')
    op.drop_index('ix_patient_conditions_patient_id', table_name='patient_conditions')
    op.drop_index('ix_patient_conditions_condition_id', table_name='patient_conditions')
    op.drop_table('patient_conditions')
    op.drop_index('ix_doctors_user_id', table_name='doctors')
    op.drop_index('ix_doctors_specialization', table_name='doctors')
    op.drop_index('ix_doctors_clinic_name', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_assistants_user_id', table_name='assistants')
    op.drop_index('ix_assistants_clinic_name', table_name='assistants')
    op.drop_table('assistants')
    op.drop_index('ix_admins_user_id', table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.drop_index('ix_patients_national_id', table_name='patients')
    op.drop_index('ix_patients_last_name', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_medical_conditions_name', table_name='medical_conditions')
    op.drop_index('ix_medical_conditions_category', table_name='medical_conditions')
    op.drop_table('medical_conditions')
    # ### end Alembic commands ###
